### ISSUE TITLE
python文件开头添加 #!/usr/bin/env python

### ISSUE THREAD

**Issue by masx200** [obaby/mht-image-extractor#5]
`#!/usr/bin/env python`

**Comment by masx200** [comment]
为了linux上正常运行，需要这样

**Comment by masx200** [comment]
https://www.cnblogs.com/CoXieLearnPython/p/9185669.html

**Comment by obaby** [comment]
> https://www.cnblogs.com/CoXieLearnPython/p/9185669.html

基于Python多个版本各种依赖库，很多系统安装的默认的是python2。所以还是使用conda或者virtual venv来执行比较好。
