### ISSUE TITLE
如果图片中包含回车和换行的话，图片会损坏 

### ISSUE THREAD

**Issue by masx200** [obaby/mht-image-extractor#7]
如果图片中包含回车和换行的话，图片会损坏 

我是在转换了包含png图片的网页的时候发现的问题

有的png图片很大的话，确实存在中间出现回车换行符的情况

`Content-Transfer-Encoding: binary`

使用二进制存储方式的文件中会出现这个问题

https://github.com/obaby/mht-image-extractor/blob/524003c25bd1e1871d9d66fbc054865036cf6982/baby_mht_image_extractor.py#L198

这行代码导致图片中间如果出现回车换行，会漏掉

应该修改成如下，只是把开头的换行回车删掉，其他的保留
```python
if (b"\r\n" == line) and( content == b""):
```

@obaby

**Comment by masx200** [comment]
这个bug有人修吗？
@obaby

**Comment by obaby** [comment]
> 这个bug有人修吗？
> @obaby

提交个文件吧。

**Comment by obaby** [comment]
@masx200 另外我没搞明白你这一行if (b"\r\n" == line) and( content == b""):是什么目的？

**Comment by obaby** [comment]
> [测试.zip](https://github.com/obaby/mht-image-extractor/files/5268394/default.zip)
> 
> 如果图片中包含回车和换行的话，图片会损坏
> 
> 我是在转换了包含png图片的网页的时候发现的问题
> 
> 有的png图片很大的话，确实存在中间出现回车换行符的情况
> 
> `Content-Transfer-Encoding: binary`
> 
> 使用二进制存储方式的文件中会出现这个问题
> 
> https://github.com/obaby/mht-image-extractor/blob/524003c25bd1e1871d9d66fbc054865036cf6982/baby_mht_image_extractor.py#L198
> 
> 这行代码导致图片中间如果出现回车换行，会漏掉
> 
> 应该修改成如下，只是把开头的换行回车删掉，其他的保留
> 
> ```python
> if (b"\r\n" == line) and( content == b""):
> ```
> 
> @obaby

已经修复~~
